### ISSUE TITLE
Handle `root` privileges in JH instances for admins

### ISSUE THREAD

**Issue by townsenddw** [calpolydatascience/k8s-cluster-deploy#8]
Need to figure out a better way to handle `root` privileges in JH instances:
## Now:
```python
    from z2jh import get_config
    def is_admin(spawner):
      admins = get_config('auth.admin.users', [])
      if spawner.user.name in admins:
        return 'yes'
      else:
        return 'no'
    c.KubeSpawner.environment.update({
      "GRANT_SUDO": is_admin,
      "CHOWN_HOME": 'yes'
    })
```
## Problem:
The above does NOT use the internal users database. i.e. when you mark someone as an admin in the JH admin page, this does function does not respect that. Instead `root` users need to be defined in the namespaces `config.yaml` file. One might think that's the more appropriate way to do things.

**Comment by awstown** [comment]
Figured this out, finally:
```python
    # Sudo rights for JH admins and 'chowning' homes
    def is_admin(spawner): return ['no', 'yes'][spawner.user.admin]
    c.KubeSpawner.environment.update({
      "GRANT_SUDO": is_admin,
      "CHOWN_HOME": 'yes'
    })
```
